[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info

[program:uvicorn]
command=uvicorn youtubedlapi_server_infusiblecoder.app:app_asgi --host 0.0.0.0 --port 9191 --workers 1 --log-level info
autostart=true
autorestart=true
stdout_logfile=/var/log/uvicorn.log
stderr_logfile=/var/log/uvicorn_error.log

[program:celery]
command=celery -A youtubedlapi_server_infusiblecoder.app.mycele worker --loglevel=info
autostart=true
autorestart=true
stdout_logfile=/var/log/celery.log
stderr_logfile=/var/log/celery_error.log

[program:redis]
command=redis-server
autostart=true
autorestart=true